basePath: /
definitions:
  domain.Auth:
    properties:
      id:
        description: swagger:ignore
        type: string
      login:
        type: string
      password:
        type: string
      session:
        $ref: '#/definitions/domain.Session'
      verification:
        $ref: '#/definitions/domain.Verification'
    required:
    - login
    - password
    type: object
  domain.Response:
    properties:
      data:
        items: {}
        type: array
      limit:
        type: integer
      skip:
        type: integer
      total:
        type: integer
    type: object
  domain.Session:
    properties:
      expiresAt:
        type: string
      refreshToken:
        type: string
    type: object
  domain.Shop:
    properties:
      created_at:
        type: string
      description:
        type: string
      seo:
        type: string
      title:
        type: string
      user_id:
        type: string
    type: object
  domain.SignInInput:
    properties:
      login:
        type: string
      password:
        type: string
      strategy:
        type: string
    type: object
  domain.User:
    properties:
      _id:
        type: string
      created_at:
        type: string
      currency:
        type: string
      lang:
        type: string
      last_time:
        type: string
      login:
        type: string
      name:
        type: string
      online:
        type: boolean
      type:
        type: string
      uid:
        type: string
      updated_at:
        type: string
      verify:
        type: boolean
    required:
    - login
    - name
    type: object
  domain.Verification:
    properties:
      code:
        type: string
      verified:
        type: boolean
    type: object
  handler.errorResponse:
    properties:
      message:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: API Server for Handmade App
  title: Handmade API
  version: "1.0"
paths:
  /api/shops:
    get:
      consumes:
      - application/json
      description: Input params for search shops
      parameters:
      - in: query
        name: $limit
        type: integer
      - in: query
        name: $skip
        type: integer
      - in: query
        name: created_at
        type: string
      - in: query
        name: description
        type: string
      - in: query
        name: seo
        type: string
      - in: query
        name: title
        type: string
      - in: query
        name: user_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Response'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Find shops by params
      tags:
      - shop
  /api/user:
    get:
      consumes:
      - application/json
      description: Input params for search users
      parameters:
      - in: query
        name: $limit
        type: integer
      - in: query
        name: $skip
        type: integer
      - in: query
        name: _id
        type: string
      - in: query
        name: created_at
        type: string
      - in: query
        name: currency
        type: string
      - in: query
        name: lang
        type: string
      - in: query
        name: last_time
        type: string
      - in: query
        name: login
        required: true
        type: string
      - in: query
        name: name
        required: true
        type: string
      - in: query
        name: online
        type: boolean
      - in: query
        name: type
        type: string
      - in: query
        name: uid
        type: string
      - in: query
        name: updated_at
        type: string
      - in: query
        name: verify
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Response'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Find few users
      tags:
      - user
  /api/user/{id}:
    delete:
      consumes:
      - application/json
      description: Delete user
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Response'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Delete user
      tags:
      - user
    get:
      consumes:
      - application/json
      description: get user info
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Get user by Id
      tags:
      - user
    put:
      consumes:
      - application/json
      description: Update user
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: string
      - description: body for update user
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Response'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Update user
      tags:
      - user
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: Login user
      operationId: signin-account
      parameters:
      - description: credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.SignInInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: SignIn
      tags:
      - auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: Create account
      operationId: create-account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.Auth'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: SignUp
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
